# Generated by Django 3.1 on 2021-03-07 18:14

from django.db import migrations, models
import resumeAnalysis.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resume/%Y/%m/%d/', validators=[resumeAnalysis.validators.validate_resume_ext])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
