# Generated by Django 3.1 on 2020-12-27 14:43

from django.db import migrations, models
import resumeAnalysis.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resume/%Y/%m/%d/', validators=[resumeAnalysis.validators.validate_resume_ext])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
