# Generated by Django 3.1 on 2020-10-04 09:37

from django.db import migrations, models
import resumeAnalysis.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='resume/%Y/%m/%d/', validators=[resumeAnalysis.validators.validate_resume_ext]),
        ),
    ]
