# Generated by Django 3.1 on 2020-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
